import * as core from "@actions/core";
import fs from "node:fs/promises";
import path from "node:path";

const PER_PAGE = 100;

async function fetchStarredRepositories(username, token) {
    const repositories = [];
    let page = 1;

    while (true) {
        core.info(
            `Fetching starred repositories for "${username}" - page ${page}...`,
        );

        const response = await fetch(
            `https://api.github.com/users/${encodeURIComponent(
                username,
            )}/starred?per_page=${PER_PAGE}&page=${page}`,
            {
                headers: {
                    Accept: "application/vnd.github+json",
                    Authorization: `Bearer ${token}`,
                    "X-GitHub-Api-Version": "2022-11-28",
                },
            },
        );

        if (!response.ok) {
            const errorBody = await response.text();

            throw new Error(
                `GitHub API request failed: ${response.status} ${response.statusText}\n${errorBody}`,
            );
        }

        const data = await response.json();

        if (!Array.isArray(data)) {
            throw new Error(
                "Unexpected response from GitHub API. Expected an array.",
            );
        }

        // Stop when GitHub returns an empty page.
        if (data.length === 0) {
            core.info(
                `No repositories found on page ${page}. Stopping pagination.`,
            );

            break;
        }

        repositories.push(...data);

        core.info(
            `Page ${page}: fetched ${data.length} repositories. Total: ${repositories.length}`,
        );

        page++;
    }

    return repositories;
}

function generateMarkdown(username, repositories) {
    const generatedAt = new Date().toISOString();

    const header = [
        "# Starred Repositories",
        "",
        "> Automatically generated by GitHub Actions.",
        "",
        `- **User:** [${username}](https://github.com/${username})`,
        `- **Total:** ${repositories.length}`,
        `- **Last updated:** ${generatedAt}`,
        "",
        "---",
        "",
    ];

    const repositoryList = repositories.map((repository) => {
        const description =
            repository.description
                ?.replace(/\r?\n|\r/g, " ")
                .trim() || "No description provided.";

        return `- [**${repository.full_name}**](${repository.html_url}) — ${description}`;
    });

    return [
        ...header,
        ...repositoryList,
        "",
    ].join("\n");
}

async function writeMarkdownFile(outputFile, content) {
    const directory = path.dirname(outputFile);

    // Create parent directories if they do not exist.
    await fs.mkdir(directory, {
        recursive: true,
    });

    await fs.writeFile(
        outputFile,
        content,
        "utf8",
    );
}

async function run() {
    try {
        const username = core.getInput("username", {
            required: true,
        });

        const outputFile =
            core.getInput("output-file") ||
            "REPOSITORY_STAR_LIST.md";

        const token =
            core.getInput("token") ||
            process.env.GITHUB_TOKEN;

        if (!token) {
            throw new Error(
                "GitHub token is required. Provide the 'token' input.",
            );
        }

        core.startGroup(
            "GitHub Starred Repository Action",
        );

        core.info(`Username: ${username}`);
        core.info(`Output file: ${outputFile}`);
        core.info(`Repositories per request: ${PER_PAGE}`);

        core.endGroup();

        const repositories =
            await fetchStarredRepositories(
                username,
                token,
            );

        const markdown =
            generateMarkdown(
                username,
                repositories,
            );

        await writeMarkdownFile(
            outputFile,
            markdown,
        );

        core.setOutput(
            "count",
            repositories.length,
        );

        core.setOutput(
            "file",
            outputFile,
        );

        core.info(
            `Successfully generated "${outputFile}".`,
        );

        core.info(
            `Total starred repositories: ${repositories.length}`,
        );
    } catch (error) {
        if (error instanceof Error) {
            core.setFailed(error.message);
        } else {
            core.setFailed(
                "An unknown error occurred.",
            );
        }
    }
}

await run();